#!/usr/bin/env python3
from pathlib import Path
import json
ROOT=Path(__file__).parents[1]
COMMANDS={
'auth.sites.list':('GET','',False),'auth.whoami':('GET','/rest/api/3/myself',False),
'jira.issues.search':('GET','/rest/api/3/search/jql',False),'jira.issues.get':('GET','/rest/api/3/issue/{issueIdOrKey}',False),'jira.issues.create':('POST','/rest/api/3/issue',True),'jira.issues.update':('PUT','/rest/api/3/issue/{issueIdOrKey}',True),'jira.issues.delete':('DELETE','/rest/api/3/issue/{issueIdOrKey}',True),'jira.issues.transitions.list':('GET','/rest/api/3/issue/{issueIdOrKey}/transitions',False),'jira.issues.transition':('POST','/rest/api/3/issue/{issueIdOrKey}/transitions',True),'jira.issues.comments.list':('GET','/rest/api/3/issue/{issueIdOrKey}/comment',False),'jira.issues.comments.create':('POST','/rest/api/3/issue/{issueIdOrKey}/comment',True),'jira.issues.comments.update':('PUT','/rest/api/3/issue/{issueIdOrKey}/comment/{commentId}',True),'jira.issues.comments.delete':('DELETE','/rest/api/3/issue/{issueIdOrKey}/comment/{commentId}',True),'jira.issues.attachments.add':('POST','/rest/api/3/issue/{issueIdOrKey}/attachments',True),'jira.projects.list':('GET','/rest/api/3/project/search',False),'jira.projects.get':('GET','/rest/api/3/project/{projectIdOrKey}',False),
'confluence.pages.list':('GET','/wiki/api/v2/pages',False),'confluence.pages.get':('GET','/wiki/api/v2/pages/{pageId}',False),'confluence.pages.create':('POST','/wiki/api/v2/pages',True),'confluence.pages.update':('PUT','/wiki/api/v2/pages/{pageId}',True),'confluence.pages.delete':('DELETE','/wiki/api/v2/pages/{pageId}',True),'confluence.spaces.list':('GET','/wiki/api/v2/spaces',False),'confluence.spaces.get':('GET','/wiki/api/v2/spaces/{spaceId}',False),'confluence.search':('GET','/wiki/rest/api/search',False),'confluence.attachments.list':('GET','/wiki/api/v2/pages/{pageId}/attachments',False),'confluence.attachments.add':('POST','/wiki/rest/api/content/{pageId}/child/attachment',True)}
props={k:{'type':t} for k,t in {'site':'string','params':'string','body':'string','timeoutMs':'integer','confirm':'string','idempotencyKey':'string','inputPath':'string','transferRoot':'string'}.items()}
out={'schemaVersion':1,'commands':{n:{'method':m,'path':p,'mutation':mut,'inputSchema':{'type':'object','properties':props,'additionalProperties':True},'outputSchema':{'type':'object','required':['ok','schemaVersion','command','requestId','effects','provenance']}} for n,(m,p,mut) in COMMANDS.items()}}
(ROOT/'command_contracts.json').write_text(json.dumps(out,indent=2)+'\n')
manifest={'schemaVersion':1,'kind':'openclaw.harness.v1','name':'atlassian','title':'Atlassian Cloud','description':'Typed Jira Cloud v3 and Confluence Cloud v2/v1 operations with guarded mutations and stable evidence.','version':'0.1.0','entrypoint':'./atlassian.py','packageRoot':'.','whenToUse':['Operate Jira Cloud or Confluence Cloud through approved credentials'],'capabilities':['jira-cloud-v3','confluence-cloud-v2','confluence-cloud-v1-fallback','multi-site','safe-transfer'],'authModel':{'type':'basic-or-oauth-bearer','storesSecrets':False,'requiresHumanAccount':True},'commands':{n:{'description':f'{n} through Atlassian Cloud REST.','baseArgv':[n],'safetyClasses':(['externalSideEffect','humanAccountAction'] if mut else ['readOnly']),'inputSchema':out['commands'][n]['inputSchema'],'outputSchema':out['commands'][n]['outputSchema']} for n,(m,p,mut) in COMMANDS.items()}}
(ROOT/'harness.json').write_text(json.dumps(manifest,indent=2)+'\n')
